config/routes.rb
Rails.application.routes.draw do
  resources :work_tests
  get 'assign_shift/index'
  get 'show_reports/index'
  get 'teaching_assistants/index'
  get 'courses/index'
  get 'top/index'
  root "top#index"

  post '/check_data', to: "show_reports#check_data"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/teaching_assistant.rb
class TeachingAssistant < ApplicationRecord
end

app/models/teaching_assistants.rb
class TeachingAssistants < ApplicationRecord
  self.table_name = :teaching_assistants

end

app/models/tum.rb
class Tum < ApplicationRecord
end

app/models/work_test.rb
class WorkTest < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production? 
  protect_from_forgery with: :exception

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/assign_shift_controller.rb
class AssignShiftController < ApplicationController
  def index
  @course = Course.find(params[:course_id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end
end

app/controllers/show_reports_controller.rb
class ShowReportsController < ApplicationController
  def index
  end
end

app/controllers/teaching_assistants_controller.rb
class TeachingAssistantsController < ApplicationController
  def index
    @TA_data = TeachingAssistants.all
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/work_tests_controller.rb
class WorkTestsController < ApplicationController
  before_action :set_work_test, only: %i[ show edit update destroy ]

  # GET /work_tests or /work_tests.json
  def index
    @work_tests = WorkTest.all
  end

  # GET /work_tests/1 or /work_tests/1.json
  def show
  end

  # GET /work_tests/new
  def new
    @work_test = WorkTest.new
  end

  # GET /work_tests/1/edit
  def edit
  end

  # POST /work_tests or /work_tests.json
  def create
    @work_test = WorkTest.new(work_test_params)

    respond_to do |format|
      if @work_test.save
        format.html { redirect_to work_test_url(@work_test), notice: "Work test was successfully created." }
        format.json { render :show, status: :created, location: @work_test }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_tests/1 or /work_tests/1.json
  def update
    respond_to do |format|
      if @work_test.update(work_test_params)
        format.html { redirect_to work_test_url(@work_test), notice: "Work test was successfully updated." }
        format.json { render :show, status: :ok, location: @work_test }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_tests/1 or /work_tests/1.json
  def destroy
    @work_test.destroy

    respond_to do |format|
      format.html { redirect_to work_tests_url, notice: "Work test was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_test
      @work_test = WorkTest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_test_params
      params.require(:work_test).permit(:date, :start_time, :end_time, :actual_working_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_shift_helper.rb
module AssignShiftHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/show_reports_helper.rb
module ShowReportsHelper
end

app/helpers/teaching_assistants_helper.rb
module TeachingAssistantsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/work_tests_helper.rb
module WorkTestsHelper
end

app/views/assign_shift/index.html.erb
<h1>TAシフト割当画面</h1>

<body>        
    <table>
      <thead>
        <tr>
            <th>年度</th>
            <th>学期</th>
            <th>科目番号</th>
            <th>授業科目名</th>
            <th>担当教員</th>
            <th>TA割り当て可能総時間</th>
            <th>備考</th>
            <th>割り当て済み時間</th>
        </tr>
      </thead>
      <tbody>
		 <% course = @course %>
        <tr>
            <td><%= course.year%></td>
            <td><%= course.term%></td>
            <td><%= course.number%></td>
            <td><%= course.name%></td>
            <td><%= course.instructor%></td>
            <td><%= course.time_budget%></td>
            <td><%= course.description%></td>
            <td>0</td>
        </tr>     
      </tbody>
    </table>
</body>

<p><%= link_to '科目一覧画面', '/courses/index' %></p>
<p><%= link_to '帳票表示画面', '/show_reports/index' %></p>

app/views/courses/index.html.erb
<h1>科目一覧画面</h1>
<body>        
    <table>
      <thead>
        <tr>
            <th>年度</th>
            <th>学期</th>
            <th>科目番号</th>
            <th>授業科目名</th>
            <th>担当教員</th>
            <th>TA割り当て可能総時間</th>
            <th>備考</th>
            <th>割り当て済み時間</th>
        </tr>
      </thead>
      <tbody>
        <% @courses.each do |course| %>
        <tr>
            <td><%= course.year%></td>
            <td><%= course.term%></td>
            <td><%= link_to course.number,assign_shift_index_path(course_id: course.id)%></td>
            <td><%= link_to course.name,assign_shift_index_path(course_id: course.id)%></td>
            <td><%= course.instructor%></td>
            <td><%= course.time_budget%></td>
            <td><%= course.description%></td>
            <td>0</td>
        </tr>
        <% end %>
      </tbody>
    </table>
</body>
<p><%= link_to 'TAシフト割当画面', '/assign_shift/index' %></p>
<p><%= link_to 'TOP画面に戻る', '/top/index' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SDM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/show_reports/index.html.erb
<h1>帳票表示画面</h1>
<p><%= link_to 'TOP画面に戻る', '/top/index' %></p>

app/views/teaching_assistants/index.html.erb
<h1>TA候補者一覧画面</h1>



<!-- index.html.erb -->
<%= stylesheet_link_tag "teaching_assistants" %>


<table class="table-container">
  <!-- テーブルの内容 -->
  <thead>
    <tr>
      <th>対象年度(year)</th>
      <th>学生番号(number)</th>
      <th>学年(grade)</th>
      <th>氏名(name)</th>
      <th>研究室(labo)</th>
      <th style="width: 300px;">備考(description)</th>
    </tr>
  </thead>
    <tbody>
        <% @TA_data.each do |ta| %>
        <tr>
            <td style="text-align: right;"><%= ta.year%></td>
            <td style="text-align: right;"><%= ta.number%></td>
            <td style="text-align: right;"><%= ta.grade%></td>
            <td style="text-align: left;"><%= ta.name%></td>
            <td style="text-align: left;"><%= ta.labo%></td>
            <td style="text-align: left;"><%= ta.description%></td>

        </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to 'TOP画面に戻る', '/top/index' %></p>

app/views/top/index.html.erb
<h1>TA時間管理システム</h1>

<p class="centered-text"><%= link_to '科目一覧画面', '/courses/index',class:'button-like' %></p>
<p class="centered-text"><%= link_to '帳票表示画面', '/show_reports/index', class:'button-like' %></p>
<p class="centered-text"><%= link_to 'TA候補者一覧画面', '/teaching_assistants/index', class:'button-like' %></p>

app/views/work_tests/_form.html.erb
<%= form_with(model: work_test) do |form| %>
  <% if work_test.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(work_test.errors.count, "error") %> prohibited this work_test from being saved:</h2>

      <ul>
        <% work_test.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.time_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.time_field :end_time %>
  </div>

  <div>
    <%= form.label :actual_working_time, style: "display: block" %>
    <%= form.number_field :actual_working_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/work_tests/_work_test.html.erb
<div id="<%= dom_id work_test %>">
  <p>
    <strong>Date:</strong>
    <%= work_test.date %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= work_test.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= work_test.end_time %>
  </p>

  <p>
    <strong>Actual working time:</strong>
    <%= work_test.actual_working_time %>
  </p>

</div>

app/views/work_tests/edit.html.erb
<h1>Editing work test</h1>

<%= render "form", work_test: @work_test %>

<br>

<div>
  <%= link_to "Show this work test", @work_test %> |
  <%= link_to "Back to work tests", work_tests_path %>
</div>

app/views/work_tests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Work tests</h1>

<div id="work_tests">
  <% @work_tests.each do |work_test| %>
    <%= render work_test %>
    <p>
      <%= link_to "Show this work test", work_test %>
    </p>
  <% end %>
</div>

<%= link_to "New work test", new_work_test_path %>

app/views/work_tests/new.html.erb
<h1>New work test</h1>

<%= render "form", work_test: @work_test %>

<br>

<div>
  <%= link_to "Back to work tests", work_tests_path %>
</div>

app/views/work_tests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @work_test %>

<div>
  <%= link_to "Edit this work test", edit_work_test_path(@work_test) %> |
  <%= link_to "Back to work tests", work_tests_path %>

  <%= button_to "Destroy this work test", @work_test, method: :delete %>
</div>